#!/bin/bash
DIRS="build-icpc-avx build-icpc-avx512 build-clang-avx build-clang-avx-openmp build-clang-avx-openmp-mpi build-clang-avx-mpi"

for D in $DIRS
do
  echo $D
  mkdir -p $D
  cd $D
  ../configure-commands $D
  cd ..
done
