modules_cc =\
  Modules/ADWF.cc \
  Modules/AWilson.cc \
  Modules/CMeson.cc \
  Modules/GLoad.cc \
  Modules/GRandom.cc \
  Modules/GUnit.cc \
  Modules/MQuark.cc \
  Modules/SolRBPrecCG.cc \
  Modules/SrcPoint.cc \
  Modules/SrcZ2.cc

modules_hpp =\
  Modules/ADWF.hpp \
  Modules/AWilson.hpp \
  Modules/CMeson.hpp \
  Modules/GLoad.hpp \
  Modules/GRandom.hpp \
  Modules/GUnit.hpp \
  Modules/MQuark.hpp \
  Modules/SolRBPrecCG.hpp \
  Modules/SrcPoint.hpp \
  Modules/SrcZ2.hpp

