#!/bin/bash

DIRS="clang-avx clang-avx-openmp clang-avx-openmp-mpi clang-avx-mpi clang-avx2 clang-avx2-openmp clang-avx2-openmp-mpi clang-avx2-mpi icpc-avx icpc-avx2 icpc-avx512 g++-sse4 g++-avx"

for D in $DIRS
do
  mkdir -p builds/$D
  cd builds/$D
  ../../scripts/configure-commands $D
  cd ../..
done
