#!/usr/bin/env bash

home=`pwd`

# library Make.inc
cd $home/Grid
HFILES=`find . -type f -name '*.h' -not -name '*Hdf5*' -not -path '*/gamma-gen/*' -not -path '*/Old/*' -not -path '*/Eigen/*'`
HFILES="$HFILES"
CCFILES=`find . -type f -name '*.cc' -not -path '*/gamma-gen/*' -not -name '*Communicator*.cc' -not -name '*SharedMemory*.cc' -not -name '*Hdf5*'`
HPPFILES=`find . -type f -name '*.hpp'`
echo HFILES=$HFILES $HPPFILES > Make.inc
echo >> Make.inc
echo CCFILES=$CCFILES >> Make.inc



# tests Make.inc
cd $home/tests
dirs=`find . -type d -not -path '*/\.*'`
for subdir in $dirs; do
    cd $home/tests/$subdir
    pwd
    TESTS=`ls T*.cc`
    TESTLIST=`echo ${TESTS} | sed s/.cc//g `
    PREF=`[ $subdir = '.' ] && echo noinst || echo EXTRA`
    echo "tests-local: ${TESTLIST} " > Make.inc
    echo ${PREF}_PROGRAMS = ${TESTLIST} >> Make.inc
    echo >> Make.inc
    HADLINK=`[ $subdir = './hadrons' ] && echo '-lHadrons '`
    for f in $TESTS; do
	   BNAME=`basename $f .cc`
	   echo ${BNAME}_SOURCES=$f >> Make.inc
	   echo ${BNAME}_LDADD=${HADLINK}-lGrid  >> Make.inc
	   echo >> Make.inc
    done
    if [ $subdir != '.' ]; then
       echo CLEANFILES = ${TESTLIST} >> Make.inc
       echo >> Make.inc
    fi
done

# benchmarks Make.inc
cd $home/benchmarks
echo> Make.inc
TESTS=`ls B*.cc`
TESTLIST=`echo ${TESTS} | sed s/.cc//g `
echo bin_PROGRAMS = ${TESTLIST} > Make.inc
echo >> Make.inc
for f in $TESTS; do
    BNAME=`basename $f .cc`
    echo ${BNAME}_SOURCES=$f  >> Make.inc
    echo ${BNAME}_LDADD=-lGrid>> Make.inc
    echo >> Make.inc
done
cd ..


# HMC Make.inc
cd $home/HMC
echo> Make.inc
TESTS=`ls *.cc`
TESTLIST=`echo ${TESTS} | sed s/.cc//g `
echo bin_PROGRAMS = ${TESTLIST} > Make.inc
echo >> Make.inc
for f in $TESTS; do
    BNAME=`basename $f .cc`
    echo ${BNAME}_SOURCES=$f  >> Make.inc
    echo ${BNAME}_LDADD=-lGrid>> Make.inc
    echo >> Make.inc
done
cd ..
