#!/bin/bash

export LANG=C
find . -name "*.cc" -print -exec sed -e "s/${1}/${2}/g" -i .bak {} \;
find . -name "*.h" -print -exec sed -e "s/${1}/${2}/g" -i .bak {} \;
find . -name "*.bak" -exec rm -f {} \;
