modules_cc =\
  Modules/MContraction/WeakHamiltonianNonEye.cc \
  Modules/MContraction/WeakNeutral4ptDisc.cc \
  Modules/MContraction/WeakHamiltonianEye.cc \
  Modules/MScalar/FreeProp.cc \
  Modules/MScalar/ChargedProp.cc \
  Modules/MGauge/Unit.cc \
  Modules/MGauge/Random.cc \
  Modules/MGauge/StochEm.cc \
  Modules/MGauge/Load.cc

modules_hpp =\
  Modules/MLoop/NoiseLoop.hpp \
  Modules/MFermion/GaugeProp.hpp \
  Modules/MContraction/WeakHamiltonian.hpp \
  Modules/MContraction/Meson.hpp \
  Modules/MContraction/DiscLoop.hpp \
  Modules/MContraction/WeakHamiltonianEye.hpp \
  Modules/MContraction/Baryon.hpp \
  Modules/MContraction/WeakHamiltonianNonEye.hpp \
  Modules/MContraction/WeakNeutral4ptDisc.hpp \
  Modules/MContraction/Gamma3pt.hpp \
  Modules/MSource/Z2.hpp \
  Modules/MSource/SeqGamma.hpp \
  Modules/MSource/Point.hpp \
  Modules/MSource/Wall.hpp \
  Modules/MSource/Laplacian.hpp \
  Modules/MSolver/RBPrecCG.hpp \
  Modules/MScalar/ChargedProp.hpp \
  Modules/MScalar/FreeProp.hpp \
  Modules/MScalar/Scalar.hpp \
  Modules/MAction/DWF.hpp \
  Modules/MAction/Wilson.hpp \
  Modules/MGauge/StochEm.hpp \
  Modules/MGauge/Unit.hpp \
  Modules/MGauge/Random.hpp \
  Modules/MGauge/Load.hpp \
  Modules/MSink/Point.hpp

