modules_cc =\
  Modules/MGauge/Load.cc \
  Modules/MGauge/Random.cc \
  Modules/MGauge/Unit.cc

modules_hpp =\
  Modules/MAction/DWF.hpp \
  Modules/MAction/Wilson.hpp \
  Modules/MContraction/Meson.hpp \
  Modules/MGauge/Load.hpp \
  Modules/MGauge/Random.hpp \
  Modules/MGauge/Unit.hpp \
  Modules/MSolver/RBPrecCG.hpp \
  Modules/MSource/Point.hpp \
  Modules/MSource/Z2.hpp \
  Modules/Quark.hpp

